spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/adaptive_learning_db
spring.datasource.username=root
# Thay mat khau theo may local cua ban
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Logging
logging.level.root=WARN
logging.level.com.datn=INFO
logging.level.org.springframework.web=WARN
logging.level.org.springframework.security=WARN
logging.level.org.springframework.boot.autoconfigure=WARN
logging.level.org.hibernate=WARN
logging.level.com.zaxxer.hikari=WARN
logging.level.org.apache.catalina=WARN
logging.level.org.apache.tomcat=WARN

server.port=8080

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
